from setuptools import setup, find_packages

setup(
    name="gtm",
    version="0.1",
    packages=find_packages(include=["gtm", "gtm.*"]),
    description="Graphical Transformation Models (GTM)",
    author="Matthias Herp",
    install_requires=[
        "matplotlib==3.8.0",
        "numpy>=1.22,<2.0",
        "optuna==3.5.0",
        "pandas==2.2.3",
        "scipy==1.15.3",
        "seaborn==0.13.2",
        "setuptools==68.2.2",
        "torch==2.5.1",
        "tqdm==4.65.0",
        "networkx==3.2.1",
        "pyvinecopulib==0.7.3",
        "scikit_learn==1.2.0",
    ],  # from requirements.txt which was generated by running pipreqs . --force in the root directory in a terminal
)
