FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10-dev \
    python3-pip \
    libffi-dev \
    build-essential \
    rsync


WORKDIR /mnt


RUN pip3 install mlflow==1.30.1
RUN pip3 install numpy==1.26.4
RUN pip3 install pandas==2.3.3
RUN pip3 install matplotlib==3.10.8
RUN pip3 install seaborn==0.13.2
RUN pip3 install scipy==1.15.3
RUN pip3 install scikit-learn==1.7.2
RUN pip3 install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu121
RUN pip3 install tqdm==4.67.1
RUN pip3 install statsmodels==0.14.6
RUN pip3 install optuna==4.7.0
RUN pip3 install torch-ema==0.3
RUN pip3 install networkx==3.4.2
RUN pip3 install pingouin==0.5.5
RUN pip3 install plotly==6.5.2
RUN pip3 install normflows==1.7.3 # added new
