FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10-dev \
    python3-pip \
    libffi-dev \
    build-essential \
    rsync \
    graphviz libgl1 libglib2.0-0 libxrender1 libsm6 libxext6 \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /mnt


RUN pip3 install mlflow
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install matplotlib
RUN pip3 install seaborn
RUN pip3 install scipy
RUN pip3 install scikit-learn
RUN pip3 install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124
RUN pip3 install tqdm
RUN pip3 install statsmodels
RUN pip3 install optuna
RUN pip3 install torch-ema
RUN pip3 install networkx
RUN pip3 install pingouin
RUN pip3 install plotly
